// StatusModel.mc — Singleton holding the history deque the watch displays
// (newest at top, oldest at bottom) and the in-progress spinner animation.
//
// Each entry is a dictionary {:icon, :flags, :text, :ts} produced by
// HistoryDecoder.decodeFrame.  When a frame arrives with
// FLAG_CLEAR_PREV_SPINNER set, the matching prior in-progress entry's
// SPINNER flag is cleared in place.

using Toybox.Graphics;
using Toybox.Lang;
using Toybox.Time;
using Toybox.Timer;
using Toybox.WatchUi;

module StatusModel {
    // ------------------------------------------------------------------
    // History buffer (cap WATCH_HISTORY_MAX)
    // ------------------------------------------------------------------

    const WATCH_HISTORY_MAX = 10;

    var entries as Lang.Array<Lang.Dictionary> = []; // [{ :icon, :flags, :text, :ts }, ...]
    var isConnected = false;
    var lastUpdateTime = null;

    // Coarse phase of the BLE state machine, surfaced through getStatusKey()
    // when no central is connected so the footer reports "sys.status:
    // scanning" / "connecting" / "discovering" / "subscribing" instead of a
    // flat "offline".  Drives no behaviour — purely display.
    var connectionPhase = "offline";

    // ------------------------------------------------------------------
    // Spinner animation (rendered on entries with FLAG_SPINNER set)
    //
    // Pre-rendered glyph bitmaps loaded from resources/drawables
    // (generated by tools/build_spinner_frames.py).  Every status glyph
    // and every spinner frame is an identically-sized PNG so column
    // alignment is pixel-perfect regardless of proportional font metrics.
    //
    // Spinner: 7 frames [·] [✦] [✧] [✶] [✷] [✸] [✹] cycled at 150 ms.
    // Static:  8 glyphs [+] [-] [~] [!] [?] [x](2) [.] at fixed colors.
    // ------------------------------------------------------------------

    const SPINNER_FRAME_COUNT = 7;
    const SPINNER_INTERVAL_MS = 150;

    // Glyph bitmap indices — used by IconCatalog.glyphBitmapIndex().
    const GLYPH_PLUS_GREEN = 0;
    const GLYPH_MINUS_WHITE = 1;
    const GLYPH_TILDE_CHROME = 2;
    const GLYPH_BANG_AMBER = 3;
    const GLYPH_QUESTION_AMBER = 4;
    const GLYPH_X_CHROME = 5;
    const GLYPH_X_AMBER = 6;
    const GLYPH_DOT_WHITE = 7;

    var spinnerFrame = 0;
    var spinnerTimer = null;
    var spinnerBitmaps as Lang.Array<WatchUi.BitmapResource>? = null;
    var glyphBitmaps as Lang.Array<WatchUi.BitmapResource>? = null;

    // Blinking block cursor for the newest row.  Toggled every 3 shared
    // spinner-timer ticks (≈ 450 ms on/off) so we only use one timer.
    const CURSOR_BLINK_TICKS = 3;
    var cursorVisible = true;
    var cursorTicks = 0;

    // ------------------------------------------------------------------
    // Lifecycle
    // ------------------------------------------------------------------

    function initialize() {
        entries = [];
        isConnected = false;
        lastUpdateTime = null;
        connectionPhase = "offline";
        spinnerFrame = 0;
        if (spinnerTimer != null) {
            spinnerTimer.stop();
            spinnerTimer = null;
        }
        cursorVisible = true;
        cursorTicks = 0;
        _loadBitmaps();
        _ensureSpinnerTimer();
    }

    function _loadBitmaps() {
        // Load once.  loadResource has non-trivial cost; cache the result.
        if (spinnerBitmaps == null) {
            spinnerBitmaps = [
                WatchUi.loadResource(Rez.Drawables.Spinner0),
                WatchUi.loadResource(Rez.Drawables.Spinner1),
                WatchUi.loadResource(Rez.Drawables.Spinner2),
                WatchUi.loadResource(Rez.Drawables.Spinner3),
                WatchUi.loadResource(Rez.Drawables.Spinner4),
                WatchUi.loadResource(Rez.Drawables.Spinner5),
                WatchUi.loadResource(Rez.Drawables.Spinner6),
            ];
        }
        if (glyphBitmaps == null) {
            glyphBitmaps = [
                WatchUi.loadResource(Rez.Drawables.GlyphPlusGreen), // 0
                WatchUi.loadResource(Rez.Drawables.GlyphMinusWhite), // 1
                WatchUi.loadResource(Rez.Drawables.GlyphTildeChrome), // 2
                WatchUi.loadResource(Rez.Drawables.GlyphBangAmber), // 3
                WatchUi.loadResource(Rez.Drawables.GlyphQuestionAmber), // 4
                WatchUi.loadResource(Rez.Drawables.GlyphXChrome), // 5
                WatchUi.loadResource(Rez.Drawables.GlyphXAmber), // 6
                WatchUi.loadResource(Rez.Drawables.GlyphDotWhite), // 7
            ];
        }
    }

    // ------------------------------------------------------------------
    // Mutators
    // ------------------------------------------------------------------

    // Apply a freshly decoded frame to the history deque.
    //
    // Entry shape: { :icon, :statusIcon, :flags, :text, :ts }
    //   • :icon       — the original tool icon, drives the intent label
    //                   (PENCIL → "edit", PLAY → "run", …).
    //   • :statusIcon — overrides the icon used for the column-1 status
    //                   glyph.  Null on a fresh entry (status follows
    //                   :icon); set to the completion icon (CHECK, PAUSE,
    //                   STOP, WARNING) when a CLEAR_PREV_SPINNER frame
    //                   collapses into the in-flight row.
    //
    // When CLEAR_PREV_SPINNER arrives, we OVERWRITE the most recent
    // in-progress entry's status instead of appending a new line.  This
    // keeps "edit: DESIGN.md" on screen and flips its `[*]` spinner to
    // `[+]` (or `[~]`/`[x]`/`[!]`) in place.  If no in-flight entry is
    // found (out-of-order events), we fall through and append normally.
    function appendEvent(frame) {
        if (frame == null) {
            return;
        }
        var inFlags = frame.get(:flags);
        if (inFlags == null) {
            inFlags = 0;
        }

        if ((inFlags & HistoryDecoder.FLAG_CLEAR_PREV_SPINNER) != 0) {
            for (var i = entries.size() - 1; i >= 0; i--) {
                var f = entries[i].get(:flags) as Lang.Number?;
                if (
                    f != null &&
                    ((f as Lang.Number) & HistoryDecoder.FLAG_SPINNER) != 0
                ) {
                    // Merge the incoming flags (e.g. ACCENT for session_error)
                    // into the matched entry, clear SPINNER, drop the directive.
                    var merged =
                        ((f as Lang.Number) & ~HistoryDecoder.FLAG_SPINNER) |
                        (inFlags &
                            ~HistoryDecoder.FLAG_SPINNER &
                            ~HistoryDecoder.FLAG_CLEAR_PREV_SPINNER);
                    entries[i].put(:flags, merged);
                    entries[i].put(:statusIcon, frame.get(:icon));
                    entries[i].put(:ts, Time.now());
                    lastUpdateTime = Time.now();
                    _ensureSpinnerTimer();
                    return;
                }
            }
            // No in-progress entry found — overwrite the most recent row
            // so session_error/idle/stop replaces the last completed entry
            // rather than appending a duplicate.
            if (entries.size() > 0) {
                var last = entries.size() - 1;
                var merged = inFlags & ~HistoryDecoder.FLAG_CLEAR_PREV_SPINNER;
                entries[last].put(:flags, merged);
                entries[last].put(:statusIcon, frame.get(:icon));
                entries[last].put(:ts, Time.now());
                lastUpdateTime = Time.now();
                _ensureSpinnerTimer();
                return;
            }
        }

        // The CLEAR_PREV_SPINNER bit is a directive, not a per-entry
        // property — strip it before storing so the rendered flags only
        // describe the entry itself.
        var storedFlags = inFlags & ~HistoryDecoder.FLAG_CLEAR_PREV_SPINNER;

        // Context inheritance: when the incoming text is empty (bare "ok",
        // "idle", etc.), borrow the icon and text from the most recent
        // entry that carries meaningful text.  The incoming icon goes to
        // :statusIcon so the glyph reflects the NEW state ([+], [~], …)
        // while the body reads as the operation that just completed.
        var inIcon = frame.get(:icon);
        var inText = frame.get(:text);
        var hasText = inText != null && (inText as Lang.String).length() > 0;

        var useIcon = inIcon;
        var useStatusIcon = null;
        var useText = inText != null ? inText : "";

        if (!hasText && entries.size() > 0) {
            for (var j = entries.size() - 1; j >= 0; j--) {
                var prevText = entries[j].get(:text) as Lang.String?;
                if (prevText != null && prevText.length() > 0) {
                    useIcon = entries[j].get(:icon);
                    useStatusIcon = inIcon; // incoming icon drives the glyph
                    useText = prevText;
                    break;
                }
            }
        }

        entries.add({
            :icon => useIcon,
            :statusIcon => useStatusIcon,
            :flags => storedFlags,
            :text => useText,
            :ts => Time.now(),
        });
        while (entries.size() > WATCH_HISTORY_MAX) {
            entries = entries.slice(1, null);
        }

        lastUpdateTime = Time.now();
        _ensureSpinnerTimer();
    }

    function setConnected(val) {
        isConnected = val;
        if (!val) {
            lastUpdateTime = null;
        }
    }

    // Updates the BLE phase surfaced by getStatusKey() when offline.
    // Accepted: "scanning" / "connecting" / "discovering" / "subscribing" /
    // "ready" / "offline".  The BleManager calls this on each transition.
    function setPhase(phase) {
        connectionPhase = phase;
    }

    // ------------------------------------------------------------------
    // Accessors
    // ------------------------------------------------------------------

    function getEntries() {
        return entries;
    }

    function getIsConnected() {
        return isConnected;
    }

    // ------------------------------------------------------------------
    // Spinner animation
    // ------------------------------------------------------------------

    function hasSpinner() {
        for (var i = 0; i < entries.size(); i++) {
            var f = entries[i].get(:flags) as Lang.Number?;
            if (
                f != null &&
                ((f as Lang.Number) & HistoryDecoder.FLAG_SPINNER) != 0
            ) {
                return true;
            }
        }
        return false;
    }

    function _ensureSpinnerTimer() {
        if (spinnerTimer == null) {
            spinnerTimer = new Timer.Timer();
            spinnerTimer.start(
                new Lang.Method(StatusModel, :_tickSpinner),
                SPINNER_INTERVAL_MS,
                true
            );
        }
    }

    function _tickSpinner() as Void {
        var changed = false;

        if (hasSpinner()) {
            spinnerFrame = (spinnerFrame + 1) % SPINNER_FRAME_COUNT;
            changed = true;
        } else if (spinnerFrame != 0) {
            spinnerFrame = 0;
            changed = true;
        }

        // Cursor blink shares this timer, so we keep blinking while idle.
        cursorTicks = cursorTicks + 1;
        if (cursorTicks >= CURSOR_BLINK_TICKS) {
            cursorTicks = 0;
            cursorVisible = !cursorVisible;
            changed = true;
        }

        if (changed) {
            WatchUi.requestUpdate();
        }
    }

    // Returns the bitmap resource for the current spinner frame, or null
    // if bitmaps failed to load (e.g. on a stripped-down device).
    function currentSpinnerBitmap() {
        if (spinnerBitmaps == null) {
            return null;
        }
        return spinnerBitmaps[spinnerFrame];
    }

    // Returns the static glyph bitmap at the given index (see
    // GLYPH_PLUS_GREEN … GLYPH_DOT_WHITE constants), or null if
    // bitmaps failed to load.
    function glyphBitmap(index) {
        if (glyphBitmaps == null) {
            return null;
        }
        if (index < 0 || index >= glyphBitmaps.size()) {
            return null;
        }
        return glyphBitmaps[index];
    }

    // ------------------------------------------------------------------
    // Helpers (kept from previous version)
    // ------------------------------------------------------------------

    function getElapsedString() {
        if (lastUpdateTime == null) {
            return null;
        }
        var delta = Time.now().subtract(lastUpdateTime).value();
        if (delta < 60) {
            return delta.toString() + "s ago";
        }
        return (delta / 60).toString() + "m ago";
    }

    function getDotColor() {
        if (!isConnected) {
            return Graphics.COLOR_RED;
        }
        if (lastUpdateTime == null) {
            return Graphics.COLOR_YELLOW;
        }
        var delta = Time.now().subtract(lastUpdateTime).value();
        return delta < 30 ? Graphics.COLOR_GREEN : Graphics.COLOR_YELLOW;
    }

    // Coarse-grained reachability state used by the CLI footer.  When the
    // central isn't connected, surfaces the current BLE phase
    // ("scanning" / "connecting" / "discovering" / "subscribing" /
    // "offline") so the user can see the watch is actively trying.  When
    // connected, returns "ok" (< 30 s since last update) or "stale".
    function getStatusKey() {
        if (!isConnected) {
            return connectionPhase;
        }
        if (lastUpdateTime == null) {
            return "stale";
        }
        var delta = Time.now().subtract(lastUpdateTime).value();
        return delta < 30 ? "ok" : "stale";
    }

    function getFooterText() {
        var key = getStatusKey();
        if (key.equals("offline")) {
            return "sys.status: offline";
        }
        var elapsed = getElapsedString();
        if (elapsed == null) {
            return "sys.status: " + key;
        }
        return "sys.status: " + key + " · " + elapsed;
    }
}
